### ISSUE TITLE
Remove moment pipe use of DateTimeElementComponent

### ISSUE THREAD

**Issue by oferah** [taldor-ltd/angular-grid-cell#19]
We should remove moment pipe use of DateTimeElementComponent, with the following reasons:
* Simplify the `html` file
* Remove `ngx-moment` dependency from this project

**Comment by benshabatnoam** [comment]
Now that we'll remove `ngx-moment`, we need to replace our `moment-pipe.enum` as it is an `ngx-moment` enum valued.
We need a different enum that will match `moment.js` function (e.g. [fromNow](https://momentjs.com/docs/#/displaying/fromnow/))
