### ISSUE TITLE
Fallback image

### ISSUE THREAD

**Issue by benshabatnoam** [taldor-ltd/angular-grid-cell#9]
When the user defines an ImageColumn ( #7 ), give him the ability to define a Fallback image path in case the original path image failed to load.

**Comment by LiorBaraban** [comment]
I'm opening a feature branch for this

**Comment by LiorBaraban** [comment]
Done.
Commit:  dbc7aa0f157ce28877006a9e4c8c64020b6045fc 
@benshabatnoam  please review and merge to master

**Comment by benshabatnoam** [comment]
Nice job Lior!

Unfortunately, found a bug with your code.
When the user pass a wrong path in the new 'errorImage' property, the site is trying to download it forever without success of-course.

**Reproduce**:
change line 28 in *simple-grid-test.component.ts* file from:
`new Column(new ImageColumnElement((data)=>data.pic,{ errorImage: "/assets/img/bad.png" }),{header: 'image'})`

to:
`new Column(new ImageColumnElement((data)=>data.pic,{ errorImage: "/assets/img/bad1.png" }),{header: 'image'})`

**Comment by benshabatnoam** [comment]
Lior what do your say about this commit?
 [Show 'broken-img' when errorImage failed to load](https://github.com/taldor-ltd/angular-grid-cell/commit/b93c683307ea2946bc82a44f50e655518316db65)
It fix the issue I've found, tell me if you see something else...
